version: '3'
services:
  mongodb-source:
    image: mongo:7.0
    ports:
      - 27017:27017
    volumes:
      - ./data-source:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_DATABASE=source
  mongodb-destination:
    image: mongo:7.0
    ports:
      - 27018:27017
    volumes:
      - ./data-destination:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_DATABASE=destination
